# Generated by Django 4.1 on 2022-09-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Eshop", "0003_category_cat_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(default="", max_length=200)),
                ("price", models.IntegerField()),
                ("desc", models.TextField(max_length=1000, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Eshop.category"
                    ),
                ),
            ],
        ),
    ]
