# Generated by Django 4.1 on 2022-09-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eshop", "0004_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_imgage",
            field=models.ImageField(null=True, upload_to="upload/product/"),
        ),
    ]
