# Generated by Django 4.1 on 2022-09-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Eshop", "0005_product_product_imgage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="product_imgage", new_name="product_image",
        ),
    ]
