# Generated by Django 4.1 on 2022-10-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eshop", "0008_order_dtls_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_dtls",
            name="price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
